version: "3.1"
services:

  mongo:
    image: mongo:4.0.4-xenial
    volumes:
      - ${database_dir}:/data/db
    environment:
      - "AUTH=yes"
      - "MONGO_INITDB_ROOT_USERNAME=${db_admin_username}"
      - "MONGO_INITDB_ROOT_PASSWORD=${db_admin_password}"
      - "MONGO_INITDB_DATABASE=${cryptocurrency}"
    ports:
      - 127.0.0.1:${db_port}:27017

  block-engine:
    build:
      context: block-engine/
    depends_on:
      - mongo
    network_mode: "host"
    volumes:
      - ./block-engine/src:/src
    environment:
      - "MONGODB_ADMIN_USER=${db_admin_username}"
      - "MONGODB_ADMIN_PASS=${db_admin_password}"
      - "MONGODB_READONLY_USER=${db_readonly_username}"
      - "MONGODB_READONLY_PASS=${db_readonly_password}"
      - "MONGODB_PORT=${db_port}"
      - "MONGODB_HOST=${db_host}"
      - "CRYPTO=${cryptocurrency}"
      - "CRYPTO_USER=${cryptocurrency_rpc_username}"
      - "CRYPTO_PASS=${cryptocurrency_rpc_password}"
      - "CRYPTO_PORT=${cryptocurrency_rpc_port}"
      - "TX_ADDRESS_CACHE_LIMIT=${tx_address_cache_limit}"

  postgres:
    image: postgres:11

  web:
    build:
      context: web/
    volumes:
      - ./web/src:/app
    depends_on:
      - postgres
      - mongo
    environment:
      - "MONGODB_READONLY_USER=${db_readonly_username}"
      - "MONGODB_READONLY_PASS=${db_readonly_password}"
      - "MONGODB_PORT=${db_port}"
      - "MONGODB_HOST=${db_host}"
      - "MONGODB_NAME=${cryptocurrency}"
      - "DJANGO_SU_NAME=${web_admin_username}"
      - "DJANGO_SU_PASSWORD=${web_admin_password}"
      - "DEBUG=${api_debug}"
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
